(function (root, factory) {
  "use strict";

  const api = factory();

  if (typeof module === "object" && module.exports) {
    module.exports = api;
  }

  root.SetiAppDom = api;
})(typeof globalThis !== "undefined" ? globalThis : window, function () {
  "use strict";

  function collectElements(documentRef) {
    return {
      appWrap: documentRef.querySelector(".app-wrap"),
      settlementInteractionShield: documentRef.getElementById("settlement-interaction-shield"),
      settlementResumeButton: documentRef.getElementById("settlement-resume-button"),
      startScreen: documentRef.getElementById("start-screen"),
      startScreenStartButton: documentRef.getElementById("start-screen-start-button"),
      startScreenDailyButton: documentRef.getElementById("start-screen-daily-button"),
      startScreenContinueButton: documentRef.getElementById("start-screen-continue-button"),
      startAiDifficulty: documentRef.getElementById("start-ai-difficulty"),
      startPlayerCount: documentRef.getElementById("start-player-count"),
      startDebugEnabled: documentRef.getElementById("start-debug-enabled"),
      startDebugToggleText: documentRef.getElementById("start-debug-toggle-text"),
      startActionLogEnabled: documentRef.getElementById("start-action-log-enabled"),
      startActionLogToggleText: documentRef.getElementById("start-action-log-toggle-text"),
      startAlienOptions: documentRef.getElementById("start-alien-options"),
      startAlienCheckboxes: documentRef.querySelectorAll("[data-start-alien-id]"),
      startIndustryOptions: documentRef.getElementById("start-industry-options"),
      startIndustryCheckboxes: documentRef.querySelectorAll("[data-start-industry-label]"),
      boardShell: documentRef.getElementById("board-shell"),
      playerCommand: documentRef.getElementById("player-command"),
      playerStats: documentRef.getElementById("player-stats"),
      opponentStatGrid: documentRef.getElementById("opponent-stat-grid"),
      playerHandPanel: documentRef.getElementById("player-hand-panel"),
      playerHandFan: documentRef.getElementById("player-hand-fan"),
      reservedCardPanel: documentRef.getElementById("reserved-card-panel"),
      reservedCardFan: documentRef.getElementById("reserved-card-fan"),
      initialSelectionArea: documentRef.getElementById("initial-selection-area"),
      actionBarMain: documentRef.getElementById("action-bar-main"),
      actionLaunchButton: documentRef.getElementById("action-launch-button"),
      actionOrbitButton: documentRef.getElementById("action-orbit-button"),
      actionLandButton: documentRef.getElementById("action-land-button"),
      actionScanButton: documentRef.getElementById("action-scan-button"),
      actionAnalyzeButton: documentRef.getElementById("action-analyze-button"),
      actionPlayCardButton: documentRef.getElementById("action-play-card-button"),
      actionResearchTechButton: documentRef.getElementById("action-research-tech-button"),
      actionQuickButton: documentRef.getElementById("action-quick-button"),
      finalResultButton: documentRef.getElementById("final-result-button"),
      actionPassButton: documentRef.getElementById("action-pass-button"),
      actionConfirmButton: documentRef.getElementById("action-confirm-button"),
      actionUndoButton: documentRef.getElementById("action-undo-button"),
      actionEffectBar: documentRef.getElementById("action-effect-bar"),
      actionEffectList: documentRef.getElementById("action-effect-list"),
      actionEffectSkipButton: documentRef.getElementById("action-effect-skip-button"),
      quickActionsPanel: documentRef.getElementById("quick-actions-panel"),
      quickActionsTrades: documentRef.getElementById("quick-actions-trades"),
      dataPlaceOverlay: documentRef.getElementById("data-place-overlay"),
      dataPlaceSubtitle: documentRef.getElementById("data-place-subtitle"),
      dataPlaceActions: documentRef.getElementById("data-place-actions"),
      dataPlaceCancel: documentRef.getElementById("data-place-cancel"),
      scanTargetOverlay: documentRef.getElementById("scan-target-overlay"),
      scanTargetTitle: documentRef.getElementById("scan-target-title"),
      scanTargetSubtitle: documentRef.getElementById("scan-target-subtitle"),
      scanTargetActions: documentRef.getElementById("scan-target-actions"),
      scanTargetCancel: documentRef.getElementById("scan-target-cancel"),
      scanAction4Overlay: documentRef.getElementById("scan-action-4-overlay"),
      scanAction4Subtitle: documentRef.getElementById("scan-action-4-subtitle"),
      scanAction4Actions: documentRef.getElementById("scan-action-4-actions"),
      scanAction4Cancel: documentRef.getElementById("scan-action-4-cancel"),
      moveArrowLayer: documentRef.getElementById("move-arrow-layer"),
      alienPanels: documentRef.querySelectorAll(".alien-panel"),
      alienTraceLayers: documentRef.querySelectorAll(".alien-trace-layer"),
      alienJiuzheTraceLayers: documentRef.querySelectorAll(".alien-jiuzhe-trace-layer"),
      alienJiuzheThresholds: documentRef.querySelectorAll(".alien-jiuzhe-thresholds"),
      alienYichangdianCardAreas: documentRef.querySelectorAll(".alien-yichangdian-card-area"),
      alienFangzhouCardAreas: documentRef.querySelectorAll(".alien-fangzhou-card-area"),
      alienBanrenmaCardAreas: documentRef.querySelectorAll(".alien-banrenma-card-area"),
      alienChongCardAreas: documentRef.querySelectorAll(".alien-chong-card-area"),
      alienAmibaCardAreas: documentRef.querySelectorAll(".alien-amiba-card-area"),
      alienAomomoCardAreas: documentRef.querySelectorAll(".alien-aomomo-card-area"),
      alienRunezuCardAreas: documentRef.querySelectorAll(".alien-runezu-card-area"),
      alienBanrenmaScoremarks: documentRef.querySelectorAll(".alien-banrenma-scoremarks"),
      finalScoreGrid: documentRef.getElementById("final-score-grid"),
      finalScoreTileWraps: documentRef.querySelectorAll(".final-score-tile-wrap"),
      finalScoreTiles: documentRef.querySelectorAll(".final-score-tile"),
      reportDock: documentRef.getElementById("report-dock"),
      wheelWrap: documentRef.getElementById("wheel-wrap"),
      tokenLayer: documentRef.getElementById("token-layer"),
      buttonWrap: documentRef.getElementById("button-wrap"),
      planetsReference: documentRef.getElementById("planets-reference"),
      planetsReferenceImage: documentRef.querySelector(".planets-reference img"),
      planetsTokenLayer: documentRef.getElementById("planets-token-layer"),
      wheels: {
        1: documentRef.getElementById("wheel-1"),
        2: documentRef.getElementById("wheel-2"),
        3: documentRef.getElementById("wheel-3"),
        4: documentRef.getElementById("wheel-4"),
      },
      sectorWraps: {
        1: documentRef.getElementById("sector-wrap-1"),
        2: documentRef.getElementById("sector-wrap-2"),
        3: documentRef.getElementById("sector-wrap-3"),
        4: documentRef.getElementById("sector-wrap-4"),
      },
      spinButton: documentRef.getElementById("spin-button"),
      failsafeAiButton: documentRef.getElementById("failsafe-ai-button"),
      failsafeSkipButton: documentRef.getElementById("failsafe-skip-button"),
      failsafeRestartButton: documentRef.getElementById("failsafe-restart-button"),
      debugToggle: documentRef.getElementById("debug-toggle"),
      debugPlayerSwitchButton: documentRef.getElementById("debug-player-switch-button"),
      debugPlayerMenu: documentRef.getElementById("debug-player-menu"),
      debugRotateButton: documentRef.getElementById("debug-rotate-button"),
      debugIncomeButton: documentRef.getElementById("debug-income-button"),
      debugGainCardButton: documentRef.getElementById("debug-gain-card-button"),
      debugScoreButton: documentRef.getElementById("debug-score-button"),
      debugSectorWinButton: documentRef.getElementById("debug-sector-win-button"),
      debugAlienTraceButton: documentRef.getElementById("debug-alien-trace-button"),
      debugJiuzheButton: documentRef.getElementById("debug-jiuzhe-button"),
      debugYichangdianButton: documentRef.getElementById("debug-yichangdian-button"),
      debugFangzhouButton: documentRef.getElementById("debug-fangzhou-button"),
      debugBanrenmaButton: documentRef.getElementById("debug-banrenma-button"),
      debugChongButton: documentRef.getElementById("debug-chong-button"),
      debugAmibaButton: documentRef.getElementById("debug-amiba-button"),
      debugAomomoButton: documentRef.getElementById("debug-aomomo-button"),
      debugRunezuButton: documentRef.getElementById("debug-runezu-button"),
      debugCheatButton: documentRef.getElementById("debug-cheat-button"),
      alienTraceOverlay: documentRef.getElementById("alien-trace-overlay"),
      alienTraceTitle: documentRef.getElementById("alien-trace-title"),
      alienTraceSubtitle: documentRef.getElementById("alien-trace-subtitle"),
      alienTraceActions: documentRef.getElementById("alien-trace-actions"),
      alienTraceCancel: documentRef.getElementById("alien-trace-cancel"),
      techPanel: documentRef.getElementById("tech-panel"),
      techStage: documentRef.getElementById("tech-stage"),
      techSelectionBackdrop: documentRef.getElementById("tech-selection-backdrop"),
      techSelectionCancel: documentRef.getElementById("tech-selection-cancel"),
      playerBoardTechLayer: documentRef.getElementById("player-board-tech-layer"),
      playerBoardDataLayer: documentRef.getElementById("player-board-data-layer"),
      techTiles: [...documentRef.querySelectorAll(".tech-tile[data-tech-id]")],
      techBlueSlotOverlay: documentRef.getElementById("tech-blue-slot-overlay"),
      techBlueSlotSubtitle: documentRef.getElementById("tech-blue-slot-subtitle"),
      techBlueSlotActions: documentRef.getElementById("tech-blue-slot-actions"),
      techBlueSlotCancel: documentRef.getElementById("tech-blue-slot-cancel"),
      logToggle: documentRef.getElementById("log-toggle"),
      stateLogTab: documentRef.getElementById("state-log-tab"),
      actionLogTab: documentRef.getElementById("action-log-tab"),
      stateReadout: documentRef.getElementById("state-readout"),
      actionLogReadout: documentRef.getElementById("action-log-readout"),
      actionBriefingOverlay: documentRef.getElementById("action-briefing-overlay"),
      actionBriefingRoundLabel: documentRef.getElementById("action-briefing-round-label"),
      actionBriefingList: documentRef.getElementById("action-briefing-list"),
      actionBriefingDetailLog: documentRef.getElementById("action-briefing-detail-log"),
      actionBriefingConfirm: documentRef.getElementById("action-briefing-confirm"),
      landTargetOverlay: documentRef.getElementById("land-target-overlay"),
      landTargetTitle: documentRef.getElementById("land-target-title"),
      landTargetLabel: documentRef.querySelector(".land-target-label"),
      landTargetSelect: documentRef.getElementById("land-target-select"),
      landTargetConfirm: documentRef.getElementById("land-target-confirm"),
      landTargetCancel: documentRef.getElementById("land-target-cancel"),
      roundStatusToken: documentRef.getElementById("round-status-token"),
      roundStatusRound: documentRef.getElementById("round-status-round"),
      roundStatusTurn: documentRef.getElementById("round-status-turn"),
      publicCardPanel: documentRef.getElementById("public-card-panel"),
      publicCardRow: documentRef.getElementById("public-card-row"),
      publicBlindDrawButton: documentRef.getElementById("public-blind-draw-button"),
      cardSelectionBackdrop: documentRef.getElementById("card-selection-backdrop"),
      cardSelectionCancel: documentRef.getElementById("card-selection-cancel"),
      publicScanConfirm: documentRef.getElementById("public-scan-confirm"),
      discardSelectionBackdrop: documentRef.getElementById("discard-selection-backdrop"),
      discardSelectionCancel: documentRef.getElementById("discard-selection-cancel"),
      passReserveSelectionOverlay: documentRef.getElementById("pass-reserve-selection-overlay"),
      passReserveSelectionTitle: documentRef.getElementById("pass-reserve-selection-title"),
      passReserveSelectionSubtitle: documentRef.getElementById("pass-reserve-selection-subtitle"),
      passReserveSelectionGrid: documentRef.getElementById("pass-reserve-selection-grid"),
      passReserveSelectionStatus: documentRef.getElementById("pass-reserve-selection-status"),
      passReserveSelectionConfirm: documentRef.getElementById("pass-reserve-selection-confirm"),
      finalResultOverlay: documentRef.getElementById("final-result-overlay"),
      finalResultSubtitle: documentRef.getElementById("final-result-subtitle"),
      finalResultDownloadLog: documentRef.getElementById("final-result-download-log"),
      finalResultMinimize: documentRef.getElementById("final-result-minimize"),
      finalResultHead: documentRef.getElementById("final-result-head"),
      finalResultBody: documentRef.getElementById("final-result-body"),
      playCardActionButton: documentRef.getElementById("play-card-action-button"),
      playCardSelectionCancel: documentRef.getElementById("play-card-selection-cancel"),
      handCardPlayActionButton: documentRef.getElementById("hand-card-play-action-button"),
      cardCornerActionButton: documentRef.getElementById("card-corner-action-button"),
      movePaymentConfirm: documentRef.getElementById("move-payment-confirm"),
      movePaymentCancel: documentRef.getElementById("move-payment-cancel"),
      handScanCancel: documentRef.getElementById("hand-scan-cancel"),
      playerHandPanelTitle: documentRef.getElementById("player-hand-panel-title"),
      playerHandPanelHandCount: documentRef.getElementById("player-hand-panel-hand-count"),
      playerHandPanelTitleHint: documentRef.getElementById("player-hand-panel-title-hint"),
    };
  }

  return {
    collectElements,
  };
});
